### ISSUE TITLE
关于eval所用的image dataset以及eval.sh中的typo以及具体的流程

### ISSUE THREAD

**Issue by itsqyh** [mrwu-mac/R-Bench#1]
作者您好，目前我遇到三个问题，1. 请问所用的Open image dataset v7是test set还是validation set. 2.似乎eval.sh中需要把eval_pope.py都改为eval.py. 3. eval的具体流程是先调用utils中的draw_mask and draw_box对图片进行处理，然后应该（？）使用infer进行推理生成QA对并以提供的格式后dump json后再运行eval.sh。请问是这样的链路嘛，还有想问问这个infer的代码有提供嘛？如果有理解错误也感谢指出，希望作者能够回答~十分感谢~~

**Comment by mrwu-mac** [comment]
您好，
感谢您的指正，我们更新了代码和README，并提供解答如下，
1. validation set (v4)
2. 已更正代码
3. 对于image-level问题，直接运行LVLM的infer脚本获得输出即可；对于instance-level问题，您需要利用我们的工具对输入进行处理

如果您有其它问题也可随时提问，我们将会处理它一旦我们看到。
